### ISSUE TITLE
The IoU of pretrained models is poor

### ISSUE THREAD

**Issue by Junyu-Z** [JeffWang987/OpenOccupancy#32]
Thanks for sharing your code and pretrained models with us. I find the IoU of **mutil-modal-baseline.pth/mutil-modal-CONet.pth/lidar-baseline.pth** is significantly lower than the numbers reported in your paper. Is this phenomenon caused by the update of occupancy annotation? Looking forward your reply!

**Comment by JeffWang987** [comment]
Apologies for any confusion. The low IoU values may be attributed to the shorter training iterations (15epc instead of 24epc) and the annotation update.

To clarify, the IoU values for mutil-modal-baseline.pth/mutil-modal-CONet.pth/lidar-baseline.pth should be 0.235/0.265/0.223 respectively. For further comparison, you can refer to the metric numbers in our training logs.

We will soon update these numbers in our paper.

**Comment by Junyu-Z** [comment]
> Apologies for any confusion. The low IoU values may be attributed to the shorter training iterations (15epc instead of 24epc) and the annotation update.
> 
> To clarify, the IoU values for mutil-modal-baseline.pth/mutil-modal-CONet.pth/lidar-baseline.pth should be 0.235/0.265/0.223 respectively. For further comparison, you can refer to the metric numbers in our training logs.
> 
> We will soon update these numbers in our paper.

Congratulation on the acceptance by ICCV 2023! Recently, I'm following your work. And I would like to know when the final version paper is available.
